### ISSUE TITLE
debug with http.FileSystem

### ISSUE THREAD

**Issue by ktye** [fhs/mux9p#1]
Would it make sense for 9serve to also serve an http.FileSystem on another port for looking around?
Or are there other methods for debugging that you use?

**Comment by fhs** [comment]
If you set the `$verbose9pserve` environment variable to 2 (or greater), it should print out the 9P messages as they are received/sent. That's the method I use.

You can even override the `log.Logger` where the debugging prints are written. So, if you want to, you can create your own http server that serves the debugging prints.

As for servering the the actual 9p file system as a `http.FileSystem`, that seem very complicated. It's not clear how you'd translate between 9p and http. I don't know why you'd want to do it when you can just mount it using something like `9pfuse -D`.

**Comment by ktye** [comment]
Thanks for the hint.
My intent was how to debug 9p when working on Windows. Maybe I shouldn't do that.
